# Generated by Django 4.2.16 on 2025-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0003_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="calendar_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
